/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Id]
      ,[Name]
      ,[Mobile]
      ,[Email]
      ,[Phone]
      ,[Age]
      ,[Gender]
      ,[Height]
      ,[Weight]
      ,[City]
      ,[FitProgram]
      ,[Fees]
  FROM [DFSCodeFirst].[dbo].[Memberships]